# https://github.com/nelsonjchen/gh-pages-pelican-action
# https://github.com/marketplace/actions/github-pages-pelican-build-action
name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nelsonjchen/gh-pages-pelican-action@0.1.10
      env:
        GH_PAGES_BRANCH: site
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PELICAN_CONFIG_FILE: publishconf.py
